seo:
  site_name: Sukha Designs, A creative agency that specializes in web design, web development and photography.
  title: Sukha Designs
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image:
social: 
  instagram_username: 
  facebook_url:
design: 
  