seo:
  site_name: Sukha Designs
  title: >-
    Sukha Designs: A creative agency that specializes in web design, web
    development and photography.
  description: >-
    Sukha Designs is a creative agency that specializes in web design, web
    development & photography. We create custom designs and code fast websites
    so that you can elevate your brand or business with a unique online
    presence. 
  keywords: >-
    web design, web development, photography, social media, content creation,
    digital creation, website, photos, business, brands
  social_image:
  author:
  favicon_image:
social:
  instagram_username: https://www.instagram.com/sukha-designs
  facebook_url:
design: